### ISSUE TITLE
Request to port over community description from last year's website

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [mscraftsman/devcon2021-web#4]
Though i don't mind a PR, but i'd be grateful if descriptions for all groups be ported from 2020's website. Currently missing are the Pymug & the Mauritius Makers community.

**Comment by jochenkirstaetter** [comment]
Hi Abdur,

Great suggestion and yes, please provide a PR for the content.
We just started to have at least a landing page for DevCon 2021 online and looking forward to receive cool updates and improvements (now). The current material is far from complete and we didn't transfer everything as there might have been changes meanwhile on regards to PyMUG or MMC that we might not be aware of.

Kindly create the code and submit a PR - we are more than happy to receive them.

Cheers, JoKi

**Comment by Abdur-rahmaanJ** [comment]
Ok ^^
